name: Server Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'packages/server/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'packages/server/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Harbor registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: develop
          password: ${{ secrets.DEV_DOCKER_LOGIN_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: packages/server
          push: true
          tags: ghcr.io/local-dev-proxy/local-dev-proxy:latest
          platforms: |
            linux/arm64
